language: java

script:
  - docker build -t="msv-pedidos":latest .
  
before_install:
  - sudo apt-get update
  - echo "---------| Gerando pacote com maven!!!  |---------"
  - mvn clean package

before_deploy:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script:
    echo "---------| Gerando Tags para imagem!!!  |---------";
    docker tag msv-pedidos:latest $DOCKER_USERNAME/msv-pedidos:$TRAVIS_JOB_ID;
    docker tag msv-pedidos:latest $DOCKER_USERNAME/msv-pedidos:latest;
    echo "---------| Enviando para o Docker HUB !!!  |---------"
    docker push $DOCKER_USERNAME/msv-pedidos:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/msv-pedidos:latest;
    echo "---------| Imagem enviada com sucesso para Docker HUB !!!  |---------";
  on:
    brach: master
notifications:
  email: false
